-- ============================================================
-- ProyectoVerde — 15 plantas nuevas (flores + hierbas + interior)
-- Ejecutar en Supabase SQL Editor DESPUÉS de seed.sql
-- ============================================================

INSERT INTO plants (
    slug, name, scientific_name, description, price, stock,
    care_water, care_light, care_temp_min, care_temp_max,
    care_substrate, care_humidity, care_fertilizer, care_difficulty,
    psychological_benefits, medicinal_uses, geographical_origin,
    fun_facts, harmful_pests, recommended_repellents,
    category, size, tags, main_image, images, is_active, is_featured
) VALUES

-- 1. ROSA
(
    'rosa-miniatura',
    'Rosa Miniatura',
    'Rosa chinensis minima',
    'La reina de las flores en formato compacto. Sus pétalos en capas perfectas y fragancia inconfundible la convierten en el regalo más clásico y elegante. Disponible en rojo, rosa y blanco.',
    180.00, 20,
    'Riego regular cada 3-4 días. Mantener el sustrato húmedo pero no encharcado. Evitar mojar las hojas para prevenir hongos.',
    'Pleno sol o luz brillante, mínimo 6 horas diarias. Es la clave para una floración abundante.',
    5, 32,
    'Tierra para rosas o sustrato enriquecido con compost. pH ligeramente ácido (6.0-6.5).',
    'Media-alta. Aprecia nebulizaciones en climas secos.',
    'Fertilizante para rosas rico en potasio cada 15 días en primavera-verano para potenciar la floración.',
    'media',
    'La rosa roja es el símbolo universal del amor, pero también de la autoestima y el valor propio. Estudios en aromaterapia muestran que su fragancia reduce la ansiedad y mejora el estado de ánimo. Tener rosas en casa genera sentimientos de bienestar y conexión emocional.',
    'Los pétalos de rosa tienen propiedades antiinflamatorias y antioxidantes. Infusión de pétalos para calmar el sistema nervioso. Agua de rosas como tónico facial natural. Mermelada de pétalos con propiedades digestivas y antioxidantes.',
    'Originaria de Asia, cultivada en México desde la época colonial. Se produce comercialmente en estados como Puebla, Estado de México, Morelos y Jalisco. México es uno de los principales exportadores mundiales de rosas de corte.',
    'Existen más de 30,000 variedades de rosas registradas. La rosa más cara del mundo, la "Juliet Rose", tomó 15 años desarrollar y costó $15 millones de dólares. En México, el día de las madres y San Valentín son los picos de consumo más altos del mundo para rosas.',
    'Pulgones, araña roja, trips y hongos como la botrytis y el oidio.',
    'Pulgones: jabón potásico + aceite de neem. Hongos: bicarbonato de sodio disuelto en agua + unas gotas de jabón. Preventivo: buena circulación de aire y evitar mojar follaje.',
    'exterior', 'pequena',
    ARRAY['flores','fragante','regalo','romantica','clasica'],
    'https://images.pexels.com/photos/5706058/pexels-photo-5706058.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/5706058/pexels-photo-5706058.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, true
),

-- 2. BUGAMBILIA
(
    'bugambilia',
    'Bugambilia',
    'Bougainvillea spectabilis',
    'El símbolo floral más reconocible de México. Sus explosiones de color —desde fucsia intenso hasta naranja, blanco y morado— la convierten en una de las plantas más impactantes visualmente. Perfecta para bardas, pérgolas y macetones.',
    220.00, 15,
    'Riego moderado, dejar secar parcialmente entre riegos. Tolera la sequía una vez establecida. Reducir riego en invierno para estimular floración.',
    'Pleno sol, mínimo 6-8 horas directas. Sin sol no florece.',
    5, 40,
    'Tierra con buen drenaje. Tolera suelos pobres —el exceso de nutrientes favorece el follaje sobre las flores.',
    'Baja. Tolera ambientes secos y cálidos.',
    'Fertilizante bajo en nitrógeno y alto en fósforo y potasio para estimular floración. Cada 21 días en primavera.',
    'media',
    'La bugambilia es símbolo de vitalidad y resistencia en la cultura mexicana. Su exuberancia visual genera alegría y energía positiva en los espacios. En psicología del color, el fucsia estimula la creatividad y la confianza. Tenerla en casa genera orgullo y sentido de identidad cultural.',
    'En medicina tradicional mexicana, las hojas se usan en infusión para tratar la tos, bronquitis y asma leve. Las flores tienen propiedades antioxidantes. Las flores secas se usan como te antidiabético en algunas comunidades indígenas del sur de México.',
    'Originaria de Brasil y Sudamérica. Naturalizada y adoptada como símbolo en todo México. Es la flor oficial de ciudades como Los Cabos, Culiacán y Nuevo Laredo. Crece silvestre en zonas tropicales y subtropicales de Guerrero, Oaxaca, Colima y toda la costa del Pacífico.',
    'Lo que parecen ser pétalos de la bugambilia son en realidad brácteas modificadas —hojas que evolucionaron para atraer polinizadores. Las flores reales son pequeñas y blancas en el centro. Puede vivir más de 50 años. En Ciudad de México hay ejemplares centenarios en casonas del Centro Histórico.',
    'Pulgones y cochinilla en brotes tiernos. En general es muy resistente a plagas.',
    'Pulgones: aceite de neem + jabón potásico. Cochinilla: alcohol isopropílico. Al ser tan vigorosa, se recupera rápidamente de cualquier ataque.',
    'exterior', 'mediana',
    ARRAY['flores','endemica_mexico','color_intenso','trepadoras','resistente','patrimonial'],
    'https://images.pexels.com/photos/12010794/pexels-photo-12010794.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/12010794/pexels-photo-12010794.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, true
),

-- 3. GIRASOL
(
    'girasol-enano',
    'Girasol Enano',
    'Helianthus annuus nanus',
    'La alegría en forma de planta. Sus flores doradas que siguen al sol son símbolo de optimismo y luz. La variedad enana es perfecta para macetas y balcones, con tallos compactos de 30-50 cm y flores preciosas.',
    95.00, 25,
    'Riego regular, mantener el sustrato húmedo pero bien drenado. No tolera el encharcamiento.',
    'Pleno sol, mínimo 6-8 horas. Su nombre lo dice todo: adora el sol.',
    10, 35,
    'Sustrato universal enriquecido con compost. Buen drenaje es esencial.',
    'Media. Aprecia algo de humedad ambiental.',
    'Fertilizante equilibrado mensual durante el crecimiento. Alto en potasio al florecer.',
    'facil',
    'El girasol es una de las plantas más estudiadas en psicología positiva. Su color amarillo brillante activa la liberación de serotonina y genera estados de alegría y optimismo. Regalar girasoles transmite admiración y lealtad. Su comportamiento heliotropo —seguir el sol— es metáfora de búsqueda constante de luz y crecimiento.',
    'Las semillas de girasol son un superalimento: ricas en vitamina E, magnesio, selenio y ácidos grasos omega-6. El aceite de girasol es antiinflamatorio tópico. En fitoterapia, las flores se usan para dolores de cabeza y fiebre.',
    'Originario de América del Norte y México. Los aztecas lo cultivaban como alimento sagrado y símbolo del dios sol Tonatiuh. Actualmente México produce girasoles principalmente en Chihuahua, Sonora y Tamaulipas. La variedad silvestre crece en campos y bordes de caminos en todo el norte del país.',
    'Un girasol puede producir hasta 2,000 semillas. Los girasoles jóvenes realmente siguen el sol (heliotropismo) hasta que maduran, luego quedan fijos mirando al este para calentar a los polinizadores matutinos. Los aztecas lo representaban en coronas de oro para honrar al dios sol.',
    'Pulgones y gusanos barrenadores. Las semillas atraen pájaros.',
    'Pulgones: aceite de neem semanal. Preventivo: plantar cerca de albahaca que los repele naturalmente.',
    'exterior', 'pequena',
    ARRAY['flores','amarillo','alegria','comestible','sol','regalo'],
    'https://images.pexels.com/photos/12519554/pexels-photo-12519554.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/12519554/pexels-photo-12519554.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, false
),

-- 4. ORQUÍDEA PHALAENOPSIS
(
    'orquidea-phalaenopsis',
    'Orquídea Mariposa',
    'Phalaenopsis sp.',
    'La flor más elegante del mundo interior. Sus flores parecen mariposas en vuelo y duran semanas sin marchitarse. Símbolo de lujo accesible, es perfecta para regalos especiales y espacios que merecen algo extraordinario.',
    350.00, 10,
    'Riego muy moderado: cada 7-10 días, verter agua y dejar drenar completamente. Las raíces deben secarse entre riegos. Usar agua a temperatura ambiente.',
    'Luz indirecta brillante. Sin sol directo que quema las hojas. Una ventana con cortina traslúcida es ideal.',
    18, 30,
    'Sustrato especial para orquídeas: corteza de pino gruesa + perlita. NUNCA tierra normal.',
    'Alta. Aprecia humedad del 50-70%. Nebulizar raíces aéreas ocasionalmente.',
    'Fertilizante especial para orquídeas diluido al 25%, cada 15 días en crecimiento. Pausa en reposo.',
    'media',
    'Las orquídeas representan el refinamiento y la perfección. En espacios de trabajo o meditación, su presencia invita a la calma y la concentración. Estudios en hospitales muestran que pacientes con orquídeas en su habitación reportan menor percepción del dolor y recuperación más rápida.',
    'En medicina china tradicional, los bulbos de algunas orquídeas se usan como tónicos para el sistema inmune y la vitalidad. El pseudobulbo de Dendrobium tiene usos en medicina ayurvédica. Las orquídeas de vainilla son la fuente del extracto de vainilla natural.',
    'Con más de 28,000 especies, las orquídeas son la familia de plantas con flores más grande del mundo. México es mega-diverso en orquídeas con más de 1,200 especies nativas, especialmente en Chiapas, Oaxaca y Veracruz. La Laelia speciosa es la orquídea nacional de México.',
    'Las raíces verdes de una Phalaenopsis indican que está bien hidratada; raíces blancas/plateadas indican sed. Puede vivir décadas con los cuidados correctos. Una sola planta puede tener hasta 20 flores simultáneas. La Phalaenopsis refleja el sol en sus células de una manera única que produce el efecto "espejo" en sus pétalos.',
    'Cochinilla harinosa, hongos por exceso de humedad y pudrición de raíces por riego incorrecto.',
    'Cochinilla: alcohol isopropílico con algodón. Hongos: canela en polvo sobre cortes (antifúngico natural). Preventivo: nunca dejar agua estancada en el centro de las hojas.',
    'interior', 'mediana',
    ARRAY['flores','elegante','regalo','larga_duracion','lujo','decorativa'],
    'https://images.pexels.com/photos/15458142/pexels-photo-15458142.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/15458142/pexels-photo-15458142.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, true
),

-- 5. CEMPASÚCHIL
(
    'cempasuchil',
    'Cempasúchil',
    'Tagetes erecta',
    'La flor de los muertos, símbolo sagrado del Día de Muertos mexicano. Su intenso color naranja y su aroma único son parte del alma de México. En maceta florece de verano a otoño llenando el espacio de color y significado cultural.',
    85.00, 30,
    'Riego moderado cuando el sustrato esté parcialmente seco. Cada 4-5 días en verano.',
    'Pleno sol. Cuanto más sol, más flores y más intenso el color.',
    10, 35,
    'Sustrato bien drenado con compost. Tolera suelos pobres.',
    'Baja-media. Tolera ambientes secos.',
    'Fertilizante equilibrado mensual. Exceso de nitrógeno favorece hojas sobre flores.',
    'facil',
    'El cempasúchil forma parte de la identidad cultural mexicana más profunda. Cultivarlo conecta con las raíces prehispánicas y el respeto por los ancestros. En psicología cultural, las plantas con significado simbólico generan un sentido de pertenencia e identidad más profundo que cualquier otra decoración.',
    'Planta medicinal de uso milenario en México: antiparasitaria intestinal, antiinflamatoria y antibacteriana. Infusión de flores para cólicos digestivos y gases. Aplicación externa en heridas e irritaciones. El aceite esencial repele insectos de manera natural. Reconocida en la farmacopea herbolaria mexicana.',
    'Originaria de México y Centroamérica. Planta sagrada para los aztecas, quienes la llamaban Cempohualxochitl (flor de 20 pétalos). Crece silvestre en campos y milpas de toda la República. Se cultiva masivamente en Puebla, Estado de México, Michoacán e Hidalgo para el mercado del Día de Muertos.',
    'Los aztecas usaban el cempasúchil en ceremonias religiosas, tinturas y medicina desde hace más de 2,500 años. Se cree que el olor guía a las almas de los difuntos durante el Día de Muertos. México exporta cempasúchil a Estados Unidos, Canadá y Europa donde se ha vuelto muy popular.',
    'Pulgones ocasionalmente. Es naturalmente resistente por sus aceites esenciales repelentes. Suele usarse como planta compañera para repeler plagas de otras plantas.',
    'Al ser naturalmente repelente, raramente necesita tratamiento. Si hay pulgones: jabón potásico.',
    'exterior', 'pequena',
    ARRAY['flores','patrimonial','dia_de_muertos','medicinal','repelente_insectos','mexicana'],
    'https://images.pexels.com/photos/29302475/pexels-photo-29302475.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/29302475/pexels-photo-29302475.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, true
),

-- 6. GERANIO
(
    'geranio-rojo',
    'Geranio',
    'Pelargonium zonale',
    'La planta de balcón por excelencia. Sus flores en racimos explotando de color y su follaje aromático la hacen perfecta para ventanas, terrazas y entradas. Resiste el sol intenso y florece casi todo el año con mínimo cuidado.',
    90.00, 25,
    'Riego moderado, dejar secar ligeramente entre riegos. Es tolerante a la sequía pero florece mejor con riego regular.',
    'Pleno sol o media sombra. Mejor con al menos 4-6 horas de sol directo.',
    5, 30,
    'Sustrato bien drenado. Mezcla universal + 20% perlita.',
    'Media. Tolera ambientes secos pero aprecia algo de humedad.',
    'Fertilizante rico en potasio y fósforo cada 15 días durante floración para mantener flores abundantes.',
    'facil',
    'El geranio es la planta de balcón más popular de Europa y México por una razón: su floración constante genera alegría visual persistente. Los estudios sobre biofilia muestran que ver flores desde casa reduce el estrés matutino. Su aroma repele mosquitos de forma natural, mejorando el bienestar del hogar.',
    'Aceite esencial de geranio: ansiolítico, antidepresivo y equilibrador hormonal. Infusión de hojas para gastritis leve. Aplicación tópica del aceite para dolores musculares y articulares. Antibacteriano natural para heridas menores.',
    'Originario de Sudáfrica. En México está ampliamente naturalizado en climas templados: Ciudad de México, Puebla, Querétaro, Guanajuato, Michoacán. Es común verlo en las ventanas coloniales del Centro Histórico de muchas ciudades mexicanas.',
    'Existen más de 400 especies y miles de variedades de geranios. El aceite esencial de rosa de geranio es uno de los más caros del mundo, usado en perfumería de lujo. Los geranios pueden vivir más de 50 años con podas regulares. Se propagan fácilmente por esquejes.',
    'Mosca blanca, trips y araña roja en climas secos.',
    'Mosca blanca: trampas amarillas + jabón potásico. Araña roja: aumentar humedad + neem. Preventivo: poda regular para buena circulación de aire.',
    'exterior', 'pequena',
    ARRAY['flores','aromatica','repelente_mosquitos','balcon','facil_cuidado','colorida'],
    'https://images.pexels.com/photos/33238715/pexels-photo-33238715.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/33238715/pexels-photo-33238715.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, false
),

-- 7. VIOLETA AFRICANA
(
    'violeta-africana',
    'Violeta Africana',
    'Saintpaulia ionantha',
    'La planta de interior que florece todo el año. Sus diminutas flores en azul, morado, rosa o blanco contrastan con sus hojas aterciopeladas verde oscuro. Perfecta para escritorios, repisas y espacios con luz artificial.',
    110.00, 18,
    'Riego por la base: llena un platillo con agua y deja que la planta absorba lo que necesita por 30 minutos. Nunca mojar las hojas. Cada 5-7 días.',
    'Luz indirecta brillante. Tolera muy bien la iluminación artificial (fluorescente o LED). Ideal para oficinas y habitaciones interiores.',
    18, 27,
    'Sustrato especial para violetas africanas o tierra ligera con mucha perlita.',
    'Alta. Necesita humedad del 50-60%. No nebulizar directamente.',
    'Fertilizante específico para violetas africanas cada 15 días durante crecimiento activo.',
    'media',
    'La violeta africana es la planta favorita de coleccionistas y terapeutas hortícolas por su floración ininterrumpida. Ver flores todo el año en el interior del hogar tiene efectos documentados en la reducción de la depresión estacional. Su tamaño compacto la hace manejable y da sensación de logro al cuidarla bien.',
    'Las flores y hojas tienen propiedades antiinflamatorias y analgésicas suaves. En algunas tradiciones herbales se usa para dolores de cabeza aplicando hojas frescas en la frente. Los flavonoides de sus flores tienen actividad antioxidante.',
    'Originaria de Tanzania y Kenia. Ampliamente cultivada en todo el mundo como planta de interior desde los años 1890. En México se encuentra en viveros y hogares de todo el país, especialmente en climas templados. No crece en estado silvestre fuera de África oriental.',
    'La violeta africana NO es una violeta real —pertenece a una familia completamente diferente. Fue descubierta por el barón alemán Walter von Saint Paul en 1892. Existen más de 16,000 variedades registradas por la Sociedad Africana de Violetas. Es una de las plantas de interior más vendidas del mundo.',
    'Trips, cochinilla harinosa y pudrición por agua en las hojas o el centro.',
    'Trips: trampas azules adhesivas + spinosad. Cochinilla: alcohol en algodón. Preventivo: NUNCA mojar hojas ni el centro de la planta.',
    'interior', 'pequena',
    ARRAY['flores','todo_el_año','interior','escritorio','compacta','colorida'],
    'https://images.pexels.com/photos/7090475/pexels-photo-7090475.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/7090475/pexels-photo-7090475.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, false
),

-- 8. BEGONIA
(
    'begonia-rex',
    'Begonia Rex',
    'Begonia rex-cultorum',
    'El arte en forma de planta. Sus hojas son auténticas obras de arte: pintadas con espirales y mosaicos de plata, verde, rojo, morado y bronce. Cada hoja es única. Para quienes buscan algo verdaderamente diferente en decoración interior.',
    145.00, 12,
    'Riego moderado, dejar secar los primeros 3-4 cm de sustrato. Sensible al encharcamiento.',
    'Luz indirecta brillante a media. Sin sol directo que decolora y quema las hojas decorativas.',
    15, 28,
    'Sustrato ligero con buena aireación: tierra + perlita + algo de turba.',
    'Alta. Necesita humedad ambiental del 50-70%.',
    'Fertilizante balanceado mensual, evitando el nitrógeno excesivo.',
    'media',
    'Las begonias rex son únicas en que su principal atractivo son las hojas, no las flores. Cuidar una planta por su follaje —prestando atención a patrones y texturas sutiles— desarrolla la observación mindful y la apreciación de la belleza en lo cotidiano. Ideal para decorar espacios de trabajo o estudio.',
    'Algunas especies de begonia tienen propiedades astringentes y antiinflamatorias usadas en medicina popular latinoamericana para tratar afecciones de la piel. Los tallos jugosos de algunas variedades se han usado para tratar quemaduras leves.',
    'El género Begonia, con más de 2,000 especies, es uno de los más grandes del reino vegetal. México tiene varias especies nativas en las zonas húmedas de Chiapas, Veracruz y Oaxaca. La Begonia gracilis es endémica mexicana.',
    'Las begonias rex se propagan de una manera única: basta con enterrar una hoja con su pecíolo en sustrato húmedo para generar una planta completa. Cada begonia rex cultivada es genéticamente idéntica a su madre —son todos clones. Las hojas pueden medir hasta 30 cm de diámetro.',
    'Oidio (hongo blanco en hojas), araña roja y cochinilla harinosa.',
    'Oidio: bicarbonato de sodio + jabón + agua en spray. Araña roja: aumentar humedad ambiental + neem.',
    'interior', 'pequena',
    ARRAY['hojas_decorativas','artistico','unico','interior','coleccionable'],
    'https://images.pexels.com/photos/36480513/pexels-photo-36480513.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/36480513/pexels-photo-36480513.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, false
),

-- 9. ROMERO
(
    'romero',
    'Romero',
    'Salvia rosmarinus',
    'La planta aromática más noble de la cocina mediterránea, perfecta para el clima mexicano. Su aroma resinoso, sus pequeñas flores azules y su resistencia la hacen ideal tanto en cocina como en jardinería ornamental y medicina natural.',
    85.00, 28,
    'Riego escaso, dejar secar completamente entre riegos. Es muy tolerante a la sequía. Exceso de agua lo mata.',
    'Pleno sol o luz brillante, mínimo 6 horas. En media sombra pierde aroma.',
    -10, 38,
    'Sustrato bien drenado, ligeramente alcalino. Arena + tierra pobre. NO compost en exceso.',
    'Baja. Prefiere ambientes secos y aireados.',
    'Casi nula. Exceso de fertilizante reduce el aroma. Solo compost leve en primavera.',
    'facil',
    'El aroma del romero mejora la memoria y la concentración —estudios de la Universidad de Northumbria confirmaron que inhalar aceite esencial de romero aumenta la memoria en un 75%. Ideal en espacios de estudio. También reduce el cortisol y los síntomas de ansiedad. En aromaterapia es el estimulante cognitivo natural más estudiado.',
    'Estimulante circulatorio y digestivo. Antiinflamatorio tópico para dolores musculares y articulares. Usado en shampoos para estimular el crecimiento del cabello (tan efectivo como el minoxidil en estudios recientes). Infusión para mejorar la digestión y reducir gases. Antibacteriano natural.',
    'Originario del Mediterráneo. En México crece y se cultiva exitosamente en climas templados y semi-áridos: Bajío, Baja California, zonas altas de Oaxaca, Chihuahua y el Valle de México. Se ha naturalizado en muchas regiones montañosas.',
    'El nombre "romero" viene del latín "ros marinus" (rocío del mar) por crecer en acantilados costeros mediterráneos. Los griegos y romanos lo consideraban la planta de la memoria y la lealtad. Estudios recientes confirman que el ácido carnósico del romero protege el cerebro contra el deterioro cognitivo.',
    'Araña roja en climas secos y cochinilla harinosa ocasionalmente.',
    'Araña roja: aumentar humedad + neem. Preventivo: buena circulación de aire. Al ser aromático, repele muchos insectos naturalmente.',
    'aromatica', 'pequena',
    ARRAY['aromatica','culinaria','medicinal','memoria','repelente_insectos','mediterranea'],
    'https://images.pexels.com/photos/4750309/pexels-photo-4750309.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/4750309/pexels-photo-4750309.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, false
),

-- 10. ALBAHACA
(
    'albahaca',
    'Albahaca',
    'Ocimum basilicum',
    'El rey de las hierbas culinarias del mundo. Su aroma fresco e intenso transforma cualquier platillo y aleja los mosquitos del hogar. Crece rápido, se usa constantemente y es la puerta de entrada perfecta a la jardinería de hierbas.',
    70.00, 35,
    'Riego frecuente, mantener el sustrato uniformemente húmedo. En verano cada 2-3 días. Muy sensible a la sequía.',
    'Sol directo o luz muy brillante, mínimo 6 horas. Con poca luz se etiolará y perderá aroma.',
    15, 35,
    'Sustrato rico con buen drenaje. Tierra + compost 30%.',
    'Media-alta. Le encanta la humedad ambiental.',
    'Fertilizante nitrogenado ligero cada 3 semanas para follaje abundante.',
    'facil',
    'Cultivar hierbas comestibles en casa genera el mayor índice de autoeficacia entre todas las plantas de interior. El acto de cortar hojas frescas de tu propia planta para cocinar conecta con la autosuficiencia ancestral humana. Estudios muestran que quienes cultivan sus propias hierbas comen con mayor consciencia y disfrutan más sus comidas.',
    'Antiinflamatorio potente (eugenol). Antibacteriano y antifúngico natural. Infusión para problemas digestivos, náuseas y espasmos. Rico en vitamina K, A y magnesio. El aceite esencial alivia dolores de cabeza tensionales. Tradicionalmente usado para el estrés y la ansiedad en medicina ayurvédica.',
    'Originaria del subcontinente indio y Asia tropical. En México es una de las hierbas culinarias más populares, usada especialmente en cocina italiana, pizzas y pastas. Se produce en huertos familiares de todo el país. Crece silvestre como maleza en climas cálidos de Veracruz, Tabasco y el Caribe mexicano.',
    'La albahaca fue tan valiosa en la antigüedad que en Italia se usaba como símbolo de amor —un hombre con albahaca en la ventana señalaba que estaba listo para el matrimonio. En México, muchas abuelas la tienen en la cocina no solo por su uso culinario sino porque creen que atrae buenas energías al hogar.',
    'Pulgones, araña roja y mosca blanca. También susceptible a hongos del sustrato.',
    'Pulgones: jabón potásico. Preventivo: no regar por la noche, buena ventilación. Al ser aromática, repele muchos insectos.',
    'aromatica', 'pequena',
    ARRAY['culinaria','aromatica','medicinal','facil_cuidado','comestible','repelente_mosquitos'],
    'https://images.pexels.com/photos/13995284/pexels-photo-13995284.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/13995284/pexels-photo-13995284.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, false
),

-- 11. CALATHEA
(
    'calathea-medallion',
    'Calathea Medallion',
    'Goeppertia veitchiana',
    'La planta que vive y respira. Sus hojas con patrones de medallón en verde oscuro y plateado se doblan por la noche como manos en oración —un espectáculo natural fascinante. Purifica el aire y es completamente pet-friendly.',
    195.00, 14,
    'Riego regular con agua sin cloro o destilada. Mantener el sustrato uniformemente húmedo. Cada 5-7 días. Muy sensible al exceso de minerales del agua de la llave.',
    'Luz indirecta media-baja. Sin sol directo. Perfecta para interiores alejados de ventanas.',
    16, 29,
    'Sustrato que retenga humedad: tierra + turba + perlita. Buen drenaje es esencial.',
    'Alta, mínimo 50%. Nebulizar hojas con agua destilada o usar charola con piedras.',
    'Fertilizante diluido al 50% mensual en primavera-verano. Pausa en invierno.',
    'media',
    'La calathea tiene un movimiento nocturno llamado nictonastia —sus hojas se elevan hacia arriba al anochecer como en oración, y descienden al amanecer. Observar este ciclo natural sincroniza el ritmo circadiano del observador y genera mayor consciencia del tiempo. Es una planta meditativa en el sentido más literal.',
    'La calathea es reconocida por la ASPCA como planta completamente no tóxica para perros y gatos. En medicina amazónica, algunas especies de calathea se usan para elaborar canastos medicinales que almacenan plantas sagradas. Las hojas tienen propiedades antibacterianas suaves.',
    'Originaria de las selvas tropicales de América del Sur, especialmente Brasil. En México no crece silvestre pero es una de las plantas de interior más vendidas. Pariente de la Maranta o planta rezadora. La familia Marantaceae tiene representantes en las selvas húmedas de Chiapas y Yucatán.',
    'Las calatheas "rezan" —mueven sus hojas siguiendo un ritmo circadiano preciso, con un mecanismo de células de agua en la base del pecíolo que actúan como bisagras hidráulicas. Este movimiento funciona aunque esté en oscuridad total. Es uno de los movimientos de plantas más documentados científicamente.',
    'Araña roja (por baja humedad), trips y puntas marrones por agua con cloro.',
    'Araña roja: aumentar humedad urgentemente + neem. Puntas marrones: usar agua filtrada o dejada reposar 24 horas para que el cloro se evapore.',
    'interior', 'mediana',
    ARRAY['pet_friendly','purifica_aire','decorativa','unica','poca_luz','hojas_decorativas'],
    'https://images.pexels.com/photos/37347934/pexels-photo-37347934.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/37347934/pexels-photo-37347934.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, true
),

-- 12. ZZ PLANT (ZAMIOCULCAS)
(
    'zamioculcas-zamiifolia',
    'ZZ Plant (Zamioculcas)',
    'Zamioculcas zamiifolia',
    'La planta más resistente para principiantes y personas ocupadas. Sus hojas ovaladas verde brillante casi parecen de plástico de tan perfectas. Sobrevive semanas sin riego, prospera en poca luz y básicamente no necesita que pienses en ella.',
    165.00, 16,
    'Riego muy escaso: cada 2-3 semanas en verano, mensual en invierno. Sus rizomas almacenan agua como camello.',
    'Tolera desde casi oscuridad hasta luz indirecta brillante. Una de las pocas plantas que prospera en pasillos y baños sin ventana.',
    15, 35,
    'Sustrato bien drenado con perlita. No necesita sustrato rico.',
    'Muy baja. Tolera cualquier nivel de humedad ambiental.',
    'Fertilizante muy diluido 2-3 veces al año. No necesita más.',
    'facil',
    'La ZZ Plant es la planta de las personas que creen no tener mano verde. Su extrema resistencia desafía la narrativa de "no puedo cuidar plantas" y genera confianza. Cada vez que la ves viva y hermosa sin casi cuidarla refuerza positivamente tu autoconcepto. Es la planta perfecta para iniciar en jardinería.',
    'Purifica el aire eliminando xileno, tolueno y benceno según la NASA. PRECAUCIÓN: todas las partes de la ZZ plant son tóxicas si se ingieren. Lavar manos después de manipularla. No es adecuada para hogares con niños muy pequeños o mascotas que muerden plantas.',
    'Originaria de África oriental, desde Kenia hasta Sudáfrica. Crece en sabanas áridas y bosques secos. En México se cultiva en viveros de todo el país y es popular en oficinas y espacios comerciales por su resistencia a la negligencia y la luz artificial.',
    'La ZZ plant puede sobrevivir hasta 4 meses sin agua gracias a sus rizomas (tallos subterráneos) que almacenan agua como reserva. Crece extremadamente lento —apenas 15-20 cm por año— pero puede vivir décadas. Es tan resistente que se vende como "la planta inmortal" en algunos países.',
    'Prácticamente sin plagas. Ocasionalmente cochinilla en zonas muy secas.',
    'Preventivo: revisar mensualmente. Si hay cochinilla: alcohol isopropílico.',
    'interior', 'mediana',
    ARRAY['sin_riego_frecuente','poca_luz','purifica_aire','principiantes','oficina','indestructible'],
    'https://images.pexels.com/photos/10651639/pexels-photo-10651639.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/10651639/pexels-photo-10651639.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, false
),

-- 13. NOCHE BUENA
(
    'nochebuena',
    'Nochebuena',
    'Euphorbia pulcherrima',
    'El símbolo vegetal más icónico de la Navidad mexicana y mundial. Sus brácteas rojas (o blancas, rosadas o jaspeadas) que coronan la planta son inconfundibles. Originaria de México, es la planta más vendida del mundo en diciembre.',
    120.00, 0,
    'Riego moderado cuando el sustrato esté seco en los primeros 2 cm. Evitar encharcamiento. Agua a temperatura ambiente.',
    'Luz indirecta brillante, mínimo 6 horas. Para que las brácteas se vuelvan rojas de nuevo: necesita noches largas (14 horas de oscuridad total por 8 semanas).',
    15, 28,
    'Sustrato bien drenado, ligeramente ácido.',
    'Media. Ambiente muy seco provoca caída de hojas.',
    'Fertilizante balanceado mensual cuando está en crecimiento vegetativo.',
    'media',
    'La nochebuena es la planta de las emociones cálidas. Ver su rojo intenso activa el sistema límbico generando sensaciones de calidez, alegría y nostalgia positiva. En psicología del color, el rojo de la nochebuena estimula la energía social y los vínculos familiares —explica por qué se regala en Navidad.',
    'El látex blanco de la nochebuena es irritante —no consumir y lavar manos al podarla. Sin embargo, en medicina tradicional mexicana, las hojas se usan en cataplasmas para inflamaciones y dolores articulares externos. Las comunidades indígenas de Guerrero la usan para tratar fiebres en aplicación externa.',
    'Originaria de México — es 100% mexicana, de las zonas áridas y subtropicales de Guerrero, Oaxaca y Chiapas donde crece como arbusto silvestre de varios metros. El botánico Joel Roberts Poinsett (embajador de EE.UU. en México, 1828) la llevó a Estados Unidos, por eso en inglés se llama "Poinsettia".',
    'Es la planta de flor más vendida del mundo, superando en diciembre a todas las demás plantas juntas. México cultiva millones para exportación. La tradición de decorar con nochebuena viene de una leyenda azteca en la que la flor representa la sangre del dios del sol. La flor pequeña real es el centro amarillo; las "flores" grandes son brácteas.',
    'Mosca blanca y cochinilla son sus principales amenazas.',
    'Mosca blanca: trampas amarillas + insecticida biológico. Cochinilla: jabón potásico + neem.',
    'interior', 'mediana',
    ARRAY['flores','navidad','mexicana','patrimonial','regalo','temporada'],
    'https://images.pexels.com/photos/14766983/pexels-photo-14766983.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/14766983/pexels-photo-14766983.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, false
),

-- 14. TOMILLO
(
    'tomillo',
    'Tomillo',
    'Thymus vulgaris',
    'La hierba aromática más completa: culinaria, medicinal y ornamental al mismo tiempo. Sus minúsculas hojas concentran un aroma poderoso y sus diminutas flores lilas en primavera son un espectáculo. Perfecta para cocina de autor y medicina casera.',
    75.00, 30,
    'Riego escaso. Dejar secar completamente entre riegos. Tolera sequía mejor que el exceso de agua.',
    'Pleno sol, mínimo 6 horas. Cuanto más sol, más aceites esenciales y más aroma.',
    -15, 35,
    'Sustrato muy bien drenado y pobre. Arena + tierra magra. Odia los suelos ricos.',
    'Baja. Prefiere ambiente seco y ventilado.',
    'Casi nula. Exceso de fertilización reduce el aroma.',
    'facil',
    'El tomillo tiene uno de los aromas más terapéuticos de la fitoterapia. El timol, su principio activo, tiene efectos ansiolíticos y antidepresivos comprobados. Cocinar con hierbas frescas de tu propio jardín —especialmente tomillo— activa múltiples sentidos simultáneamente y genera uno de los estados de bienestar más completos documentados.',
    'Expectorante y antibacteriano respiratorio (el timol es el principio activo del Listerine original). Infusión para tos, bronquitis, sinusitis y dolor de garganta. Antiinfúngico externo. Antiséptico natural para heridas. Antimicrobiano en alimentos. La OMS lo reconoce como medicinal para afecciones respiratorias.',
    'Originario del Mediterráneo, naturalizado en México en zonas de clima templado y semi-árido. Se produce en Baja California, Hidalgo y el Valle de México. Crece silvestre en terrenos rocosos y secos. Las abejas lo adoran —la miel de tomillo es una de las más apreciadas del mundo.',
    'El timol del tomillo fue el primer antiséptico comercial —base del Listerine inventado en 1879. Los egipcios lo usaban para embalsamar momias. Un solo gramo de tomillo seco concentra más antioxidantes que muchas frutas frescas. Atrae polinizadores: mariposas, abejas y abejorros.',
    'Poca susceptibilidad a plagas por sus aceites esenciales. Ocasionalmente araña roja en ambientes muy secos.',
    'Araña roja: neem + aumentar humedad. Preventivo: buena circulación de aire.',
    'aromatica', 'pequena',
    ARRAY['culinaria','medicinal','aromatica','facil_cuidado','comestible','respiratorio'],
    'https://images.pexels.com/photos/4750309/pexels-photo-4750309.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/4750309/pexels-photo-4750309.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, false
),

-- 15. CILANTRO
(
    'cilantro',
    'Cilantro',
    'Coriandrum sativum',
    'La hierba definitoria de la cocina mexicana. Sin cilantro no hay taco, no hay guacamole, no hay salsa verde. Cultivarlo en casa asegura siempre tener cilantro fresco, recién cortado, sin aditivos y con el aroma más intenso posible.',
    55.00, 40,
    'Riego frecuente, mantener el sustrato húmedo. En verano cada 2-3 días. Se marchita rápido sin agua.',
    'Sol parcial o luz indirecta brillante. El exceso de sol lo hace florecer prematuramente (bolting).',
    5, 28,
    'Sustrato rico con buen drenaje. Tierra + compost 25%.',
    'Media. Aprecia algo de humedad ambiental.',
    'Fertilizante nitrogenado ligero mensual para follaje abundante.',
    'facil',
    'El cilantro está tan ligado a la identidad culinaria mexicana que cultivarlo en casa genera una conexión profunda con la cultura gastronómica nacional. Cocinar con ingredientes propios reduce el estrés y aumenta la satisfacción con la alimentación. El olor del cilantro fresco activa memorias autobiográficas positivas asociadas a comidas familiares.',
    'Digestivo, carminativo y antiespasmódico. Antiinflamatorio. Quelante de metales pesados —ayuda al cuerpo a eliminar metales tóxicos como el mercurio y el plomo. Antibacteriano contra bacterias del alimento como Salmonella. Las semillas (coriandro) son analgésicas y antidiabéticas en estudios preliminares.',
    'Originario del Mediterráneo y Medio Oriente, introducido en México en la época colonial. Completamente naturalizado —hoy es imposible imaginar la cocina mexicana sin él. Crece silvestre como maleza en jardines, campos y bordes de caminos en todo el país. Se produce comercialmente en Sinaloa, Sonora y Jalisco.',
    'El odio al cilantro es genético: las personas con variante del gen OR6A2 perciben los aldehídos del cilantro como "jabón". El coriandro (semilla del cilantro) es una de las especias más antiguas documentadas: se encontró en tumbas egipcias de 3,500 a.C. El cilantro crece tan rápido que puede cosecharse a las 3-4 semanas de plantado.',
    'Pulgones y mosca blanca ocasionalmente.',
    'Pulgones: jabón potásico. Al ser aromático, repele muchos insectos. Rotación cada 2-3 meses pues tiende a florecer y morir rápido.',
    'aromatica', 'pequena',
    ARRAY['culinaria','medicinal','tradicional_mexicana','comestible','facil_cuidado','rapido_crecimiento'],
    'https://images.pexels.com/photos/9893128/pexels-photo-9893128.jpeg?auto=compress&cs=tinysrgb&w=600&q=80',
    ARRAY['https://images.pexels.com/photos/9893128/pexels-photo-9893128.jpeg?auto=compress&cs=tinysrgb&w=800&q=80'],
    true, false
);

-- ============================================================
-- Verificar total de plantas
-- ============================================================
SELECT COUNT(*) as total_plantas,
       COUNT(CASE WHEN is_featured THEN 1 END) as destacadas
FROM plants;
